# Site settings
title: Ich hab keinen.Blog # site title
description: >- # site description
  Kurzgeschichten, Kommentare und feinste Satire von einem 20 Jährigen Taugenichts. Viel Spaß beim Lesen.
lang: de-DE # default lang
timezone: Berlin/London # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Tim # author name
  bio: Kurzgeschichten, mittelmäßige Satire und weitere Texte, die Dich hoffentlich zum Lachen bringen findest Du hier. # tell to the world
    
  username: Tim # author username
  github: github_username
  twitter: twitter_username
  facebook: facebook_username
  email: tober1203@gmail.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "http://ich-hab-keinen.blog"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
